services:
  postgres:
    image: postgres:16-alpine
    container_name: rbac-api-postgres
    environment:
      POSTGRES_USER: rbac
      POSTGRES_PASSWORD: rbac
      POSTGRES_DB: rbac_api
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U rbac -d rbac_api']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
